name: Test SSH Connection

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Test SSH connection
      run: |
        ssh -i ${{ secrets.SSH_PRIVATE_KEY }} \
        -o StrictHostKeyChecking=no \
        ropabajo@${{ secrets.SERVER_IP }} \
        'echo "SSH connection successful"'
