name: Build, Deploy, and Apply API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build the Docker image
      run: |
        docker build \
        --build-arg GITHUB_USERNAME=${{ secrets.USERNAME }} \
        --build-arg GITHUB_TOKEN=${{ secrets.TOKEN }} \
        -t ropbajo/msa-ap-objects:latest \
        -t ropbajo/msa-ap-objects:v${{ github.run_number }} .

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: |
        docker push ropbajo/msa-ap-objects:latest
        docker push ropbajo/msa-ap-objects:v${{ github.run_number }}

    - name: Checkout k8s-recipes repository
      uses: actions/checkout@v2
      with:
        repository: ropabajo/k8s-recipes
        path: k8s-recipes
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update deployment.yaml with new image version
      run: |
        sed -i 's|ropbajo/msa-ap-objects:v[0-9\.]*|ropbajo/msa-ap-objects:v${{ github.run_number }}|' k8s-recipes/ap-objects/base/deployment.yaml
        cd k8s-recipes
        git config --global user.email "robertbarrera@outlook.com"
        git config --global user.name "Robert Barrera"
        git add ap-objects/base/deployment.yaml
        git commit -m "Update image version to v${{ github.run_number }}"
        git push

    - name: SSH to the server and deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}  # El usuario que usas para Minikube (ropabajo)
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /path/to/k8s-recipes
          kubectl apply -f ap-objects/base/deployment.yaml
